### ISSUE TITLE
What did this do

### ISSUE THREAD

**Issue by 32Puschel** [iRadd/EarthMC-Scams#12]
![image](https://user-images.githubusercontent.com/68943564/145231775-6166a1de-64f1-4c7b-8bba-f54e75852b57.png)

**Comment by iRadd** [comment]
and what did you expect it to do?

**Comment by 32Puschel** [comment]
I want to know what happend I expected it to give me the rank sus

**Comment by iRadd** [comment]
suspicious or amogus?

**Comment by 32Puschel** [comment]
amogus

**Comment by iRadd** [comment]
the sus badge is a legendary badge, only the masters of masters can get it. The only way to find it is to go trough the white fores on the other side of the river, behind the big mountain. There you must finish 8 legendary quests to get the key to unlock the badge

**Comment by 32Puschel** [comment]
understandable, so nothing is broken?

**Comment by 32Puschel** [comment]
like the actual code, did I break anything

**Comment by iRadd** [comment]
no
