### ISSUE TITLE
Messages get sent twice

### ISSUE THREAD

**Issue by 32Puschel** [iRadd/EarthMC-Scams#6]
If you send commands that contain the same command twice but no username, e.g. .who .who
![image](https://user-images.githubusercontent.com/68943564/144755196-b095cdbc-808b-49dd-b046-06d7e0d9c902.png)
![image](https://user-images.githubusercontent.com/68943564/144755198-e102494b-abb2-4239-b00a-f374159b4426.png)

**Comment by iRadd** [comment]
this isn't supposed to work for a few reasons... the first reason is that most of the commands are looking for a username as it's first argument so it is searching up '.who' as it's first argument resulting in this error; however, the duplicate message is an error, so I will fix this tonight

**Comment by iRadd** [comment]
will be fixed in the next restart, which will be roughly when V2 releases...

**Comment by 32Puschel** [comment]
![image](https://user-images.githubusercontent.com/68943564/147419485-92388a10-1e74-44ec-939a-c81143fee155.png)
Did not fix it

**Comment by iRadd** [comment]
fixed, will be added in the next restart

**Comment by iRadd** [comment]
(i did it eventually @32Puschel @voltt10 @Drip9r are you all proud of me)
