### ISSUE TITLE
EarthMC scam issue

### ISSUE THREAD

**Issue by 13E666L13** [iRadd/EarthMC-Scams#8]
Something has been brought to my attention that to be honest makes me sad, while I do understand it's a part of the bot's system it still makes my heart stop beating and my blood turn cold, when I see/hear this I get goosebumps.
Quite frankly this is the worst thing EMC scams has witnessed and maybe EMC as a whole, it makes me sad and angry simultaneously.
This horrid thing is you not .complimenting me :(

**Comment by 32Puschel** [comment]
.complain

**Comment by iRadd** [comment]
![image](https://user-images.githubusercontent.com/67561864/144924673-0e9be2d5-5fcc-45d6-873e-aaeeef267f15.png)

_**done.**_
